schema {
  query: Query
  mutation: Mutation
}

type Entity {
  id: ID!
  name: String!
  size: Float
}

input EntityInput {
  name: String!
  size: Float
}

type TrainingFeatures {
  skipTrimOnCreate: Boolean!
  skipTrimOnUpdate: Boolean!
  flakyEndpoint: Boolean!
  rateLimiting: Boolean!
  slowEndpoint: Boolean!
  paginationEdgeCases: Boolean!
  bulkPartialFailures: Boolean!
  graphqlComplexityLimit: Boolean!
}

type TrainingConfig {
  enabled: Boolean!
  features: TrainingFeatures!
}

input TrainingFeaturesInput {
  skipTrimOnCreate: Boolean
  skipTrimOnUpdate: Boolean
  flakyEndpoint: Boolean
  rateLimiting: Boolean
  slowEndpoint: Boolean
  paginationEdgeCases: Boolean
  bulkPartialFailures: Boolean
  graphqlComplexityLimit: Boolean
}

input TrainingConfigInput {
  enabled: Boolean
  features: TrainingFeaturesInput
}

type Query {
  entities: [Entity!]!
  entity(id: ID!): Entity
  trainingMode: Boolean!
  trainingConfig: TrainingConfig!
}

type Mutation {
  createEntity(input: EntityInput!): Entity!
  updateEntity(id: ID!, input: EntityInput!): Entity!
  deleteEntity(id: ID!): Entity!
  updateTrainingConfig(config: TrainingConfigInput!): TrainingConfig!
}
